### ISSUE TITLE
Can not rackup

### ISSUE THREAD

**Issue by mrcook** [manuca/roda-will_paginate#2]
I have a simple blog-like Roda/Sequel test app; I've include the gem in the Gemfile and added `plugin :will_paginate` to app.rb, but when I `rackup` I get the following errors;

.../roda-will_paginate-0.0.3/lib/roda/plugins/will_paginate.rb:11: warning: toplevel constant WillPaginate referenced by Roda::WillPaginate
.../roda-will_paginate-0.0.3/lib/roda/plugins/will_paginate.rb:11:in `configure': uninitialized constant WillPaginate::LinkRenderer (NameError)

Do you have any idea why?

**Comment by manuca** [comment]
@mrcook thanks for reporting, could you checkout the latest commit from master and confirm that this has been fixed. Thanks!

**Comment by mrcook** [comment]
That fixed it. Thanks!
