### ISSUE TITLE
How to use the plugin?

### ISSUE THREAD

**Issue by mrcook** [manuca/roda-will_paginate#3]
I'm unable to figure out how to get the plugin to work. I've created a test Roda/Sequel/Postgres app. Gem is installed and `plugin :will_paginate` added. Routes have this;

```
r.root do
  @posts = Post.reverse_order(:created_at).paginate(page: 1)
  view("homepage")
end
```

And the view is like this;

```
<% @posts.each do |post| %>
  <!-- STUFF -->
<% end %>
<%= will_paginate @posts %>
```

This gives the error;

```
NoMethodError: undefined method `paginate' for Post:Class
```

Okay, perhaps I need the Sequel pagination plugin; `DB.extension(:pagination)` and change the `.paginate` to;

```
@posts = Post.reverse_order(:created_at).paginate(1, 10)
```

But this doesn't work either;

```
NoMethodError: undefined method `total_pages' for #<#<Class:0x007fa7fb6255e8>:0x007fa7fb4f4f48>
```

Obviously I'm doing something wrong, I just don't know what. Can you help?

**Comment by manuca** [comment]
Hi there once again. The thing is Will Paginate relies on some methods being defined on your collection, methods Sequel doesn't define for its results.

Take a look at the five methods defined in `CollectionMethods` at:

https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/collection.rb

If you implement those the pagination should work.
Hope this helps

**Comment by manuca** [comment]
Just to clarify, you need to implement:

```
current_page, per_page, offset, total_entries, total_pages
```

on your collection and then you can just include `WillPaginate::CollectionMethods` as methods of your collection. That should make it work.

**Comment by mrcook** [comment]
Thanks for help Manuel, I'll give that a go tomorrow.

It may be useful to include this information in the README.

**Comment by manuca** [comment]
Done, I added some comments on the README, thanks for the feedback.
